volumes:
  mysql-data:

services:
  go-on-go:
    image: ${IMAGE:-go-on-go:latest}
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
        - .:/usr/src/app

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_on_go
      MYSQL_USER: go_on_go
      MYSQL_PASSWORD: go_on_go
    ports:
    - "8306:3306"
    volumes:
    - mysql-data:/var/lib/mysql